name: bangumi_list
description: 番剧清单

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  fluro: "^1.3.1"
  redux: "^3.0.0"
  flutter_redux: "^0.5.0"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true